// <auto-generated />
using Funds.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Funds.Migrations
{
    [DbContext(typeof(FundsContext))]
    [Migration("20191122083620_Initial migration")]
    partial class Initialmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0");

            modelBuilder.Entity("Funds.Data.Fund", b =>
                {
                    b.Property<int>("FundId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("A5Return")
                        .HasColumnType("REAL");

                    b.Property<double>("AReturn")
                        .HasColumnType("REAL");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("FundTypeName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Isin")
                        .HasColumnType("TEXT");

                    b.Property<string>("Manager")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.HasKey("FundId");

                    b.HasIndex("FundTypeName");

                    b.ToTable("Funds");

                    b.HasData(
                        new
                        {
                            FundId = 1,
                            A5Return = 11.74,
                            AReturn = 14.18,
                            Category = "Renta variable",
                            Isin = "ES0180792006",
                            Manager = "Renta 4 Gestora",
                            Name = "True value FI",
                            Price = 16.309999999999999
                        });
                });

            modelBuilder.Entity("Funds.Data.FundType", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("FundTypes");

                    b.HasData(
                        new
                        {
                            Name = "Active"
                        },
                        new
                        {
                            Name = "Passive"
                        },
                        new
                        {
                            Name = "Hybrid"
                        });
                });

            modelBuilder.Entity("Funds.Data.Fund", b =>
                {
                    b.HasOne("Funds.Data.FundType", "FundType")
                        .WithMany("Funds")
                        .HasForeignKey("FundTypeName");
                });
#pragma warning restore 612, 618
        }
    }
}
